language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script: "bundle exec rake db:migrate --trace"
script: "bundle exec rake spec"
rvm:
  - 1.9.3
notifications:
  email:
    recipients:
      - sukesh@thoughtworks.com
      - ellensandell@gmail.com
    on_failure: always
